### ISSUE TITLE
Style the scrollbar

### ISSUE THREAD

**Issue by Viper-M** [GDSC-Chandigarh-University/CUnite#2]
![Screenshot (45)_LI](https://user-images.githubusercontent.com/60223871/135514414-82f0131a-7b53-451d-b79b-d2eb69b1cfc2.jpg)
Style the dashboard scrollbar like this:
![Screenshot (47)](https://user-images.githubusercontent.com/60223871/135514123-20b15c10-2ac9-4817-bc67-5d9fdbe7b207.png)
Take inspiration from Codepen or whatever
The CSS should be done inside styles/components/base.scss

**Comment by Viper-M** [comment]
https://codepen.io/tholman/details/tldwm

**Comment by Karan-Dhingra** [comment]
Done
